### ISSUE TITLE
Error when running ngx new command

### ISSUE THREAD

**Issue by alexkolt** [ngx-rocket/generator-ngx-rocket#622] opened 2021-12-15 16:54 UTC
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Question

## Current behavior
running "ngx new" command fails with error

.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/conf/dist/source/index.js:165
            throw new TypeError('Use `delete()` to clear values');
                  ^

TypeError: Use `delete()` to clear values
    at Conf.set (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/conf/dist/source/index.js:165:19)
    at Insight.set optOut [as optOut] (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/insight/lib/index.js:56:15)
    at Object.initializing (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/generators/app/index.js:57:25)
    at Object.<anonymous> (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/yeoman-generator/lib/index.js:1024:25)
    at /Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/yeoman-generator/lib/index.js:1025:11)
    at Immediate.<anonymous> (/Users/alexeikoltsov/.nvm/versions/node/v16.13.1/lib/node_modules/generator-ngx-rocket/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (node:internal/timers:464:21)

## Expected behavior
Should be able to create a new project

## Minimal reproduction of the problem with instructions
Install nvm, node, rocket generator.
Run new command.

## Environment

<pre><code>

ngx --debug-infos                                                                                                                                     ✔  08:32:00 
ngX-Rocket: 10.1.1
Node.js: v16.13.1
Npm: 8.3.0
OS: darwin arm64 21.1.0
Others:

</code></pre>

Brand new Macbook Air, running Monterey.

**Comment by Ruslancic** [comment] 2021-12-15 18:35
Just use some flag, like 

> ngx new --no-git

**Comment by sinedied** [comment] 2021-12-15 19:18
Duplicate of #620.
The fix is in the pipe

**Closed by sinedied** 2021-12-15 19:18 UTC
