### ISSUE TITLE
Not compatible with tsconfig strict: true

### ISSUE THREAD

**Issue by sandangel** [ngx-rocket/generator-ngx-rocket#163] opened 2017-10-31 03:02 UTC
## I'm submitting a...

[x] Bug report  
[x] Feature request
[ ] Documentation issue or request

## Current behavior

Not compatible with tsconfig strict: true

## Expected behavior

compatible with tsconfig strict: true

## Minimal reproduction of the problem with instructions

Generate new project and enable strict: true in tsconfig.json

## Environment

```
- generator version: all
- node version: 8.8.1  <!-- run `node --version` -->
- npm version: 5.5.1  <!-- run `npm --version` -->
- OS:  Mac, Linux, Windows 
```

Others:

**Comment by sinedied** [comment] 2017-10-31 11:05
For now, this is by design.
We use the same tsconfig used by angular-cli projects, for compatibility. From my test run, errors pops even in Angular itself, so even if issues from this project were fixed, it would not build.
Note also that most errors are due to the `strictNullChecks` flag being enabled, which trades type safety at hurt of readability/simplicity, though that's debatable 😄 

This may change in the future though, so I'm keeping this issue open.

**Comment by sandangel** [comment] 2017-10-31 11:34
angular4 is not compatible with strictNullCheck but angular 5 does. I had checked with angular 5rc9.

**Comment by sinedied** [comment] 2017-10-31 19:40
That's good news, so we may take a look a this once Angular 5 is released.

**Comment by sinedied** [comment] 2017-11-21 19:51
Done with limitations when using Ionic, see #182 for details.
Will be released with next version 😉

**Closed by sinedied** 2017-11-21 19:51 UTC
Labels: feature, PR-welcome
