### ISSUE TITLE
App failed to compile upon save

### ISSUE THREAD

**Issue by peterson-umoke** [ngx-rocket/generator-ngx-rocket#367] opened 2018-08-24 20:13 UTC
## I'm submitting a...

- [* ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

once i save any file after running yarn start, it shows this 
Failed to compile.

./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@angular/router.ngfactory' in 'C:\xampp\htdocs\WebAPPSEngine\src\app'

## Expected behavior

i expect the app to reload and show the new updated change

## Minimal reproduction of the problem with instructions

lauch a new app, running the latest cli and yarn, create the new app and install any new npm package say, angularfire2, firebase and  classlist.js, change any file, and the issue will just begin

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment] 2018-08-31 12:56
Duplicate of https://github.com/ngx-rocket/generator-ngx-rocket/issues/352 and https://github.com/ngx-rocket/generator-ngx-rocket/issues/366, please see the fix in https://github.com/ngx-rocket/generator-ngx-rocket/issues/366.

**Closed by sinedied** 2018-08-31 12:56 UTC
