### ISSUE TITLE
Language dropdown not working on the LOGIN screen

### ISSUE THREAD

**Issue by bostondevin** [ngx-rocket/generator-ngx-rocket#169] opened 2017-11-06 13:41 UTC
## I'm submitting a...

[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

Language dropdown does not change the language labels on the Login Screen

## Expected behavior

Language labels (username, password, remember me, etc) should change

## Minimal reproduction of the problem with instructions

Change label 

Related to https://github.com/ngx-rocket/generator-ngx-rocket/issues/165

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment] 2017-11-06 13:52
I cannot reproduce this with the latest `2.3.1` release, did you update as explained in #165 ?

You should have commented on the previous issue instead of creating a new one, that would help to  follow for others landing on this 😉

**Comment by sinedied** [comment] 2017-11-13 09:32
I'm closing this issue since it cannot be reproduced, feel free to report here if it's still not working.

**Closed by sinedied** 2017-11-13 09:32 UTC
