### ISSUE TITLE
cannot run ionic serve

### ISSUE THREAD

**Issue by RamyEl-basyouni** [ngx-rocket/generator-ngx-rocket#344] opened 2018-07-23 13:03 UTC
I am seeing that ionic serve is not handled in package.json scripts, however i tried ionic-app-scripts serve
but always getting cannot find "src/theme/variables.scss"

**Comment by sinedied** [comment] 2018-07-23 13:12
The Ionic CLI cannot build Angular CLI project (seems that it's what you're trying to do from your error), you need to use the NPM scripts of the project as stated in the docs.

**Comment by RamyEl-basyouni** [comment] 2018-07-24 12:09
if you mean ngx scripts then yes i am using them, the issue behind that i cannot find it is an ionic solution, no main.ts file and ionic.config, i am seeing that the structure is generated with angular routing which does not make sense is ionic.
Actually is generated as mixed ionic and web project not only ionic. Does it make sense?

Thanks

**Comment by sinedied** [comment] 2018-07-24 16:49
The generated projects are Angular CLI projects, that's all. When the Ionic UI option is selected, it makes use of the Ionic *framework*, but not the Ionic *CLI*. The Ionic CLI is not currently compatible with Angular CLI (that may change with upcoming v4).
The project structure follows Angular projects' best practices as described in the [Angular style guide](https://angular.io/guide/styleguide), which is different from projects generated by the Ionic *CLI* and this is by design.

**Comment by RamyEl-basyouni** [comment] 2018-07-28 20:34
So There is no way to create Ionic structured application using ionic cli without angular routing and others inteferring the core of the ionic project soon ?

**Comment by sinedied** [comment] 2018-07-30 06:49
@RamyEl-basyouni No, if you want that then just use the Ionic CLI directly

**Comment by sinedied** [comment] 2018-09-07 13:29
Closing, as Ionic CLI support is out of the scope of this project (and it won't matter anyways with the upcoming Ionic 4 version 😉 )

**Closed by sinedied** 2018-09-07 13:29 UTC
Labels: question
