### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Alexander-Fuchs** [ngx-rocket/generator-ngx-rocket#432] opened 2019-01-17 08:28 UTC
## I'm submitting a...
- [x] Bug report  ? 
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
I am using HttpClient in AuthenticationService and created an JwtInterceptor.
This JwtInterceptor is added to the HttpServer the same way as the ApiPrefixInterceptor.
When importing the AuthenticationService in the JwtInterceptor it runs into an "Maximum call stack size exceeded".
As debugging shows, the HttpService constructor is called infinitely -> which causes the "Maximum call stack size exceeded".
Update: If i dont use your HttpService it is working... (adding the interceptors to the app.core providers) 

## Expected behavior
No "Maximum call stack size exceeded"?

## Environment
Current ngx-rocket generator with bootstrap and authentication.

**Comment by sinedied** [comment] 2019-01-21 08:12
I guess you're importing `HttpService` in your `AuthenticationService` then?
If that's the cause, this is the root of your issue, as your are creating an import loop. It's not caught at build time as `HttpService` creates new instance each time to allow changing interceptors dynamically.

To solve this, the simplest way is to create a new independant service to store your credentials (JWT token), and import this service in `AuthenticationService` and `JwtInterceptor` and remove any reference in your interceptor to `AuthenticationService` if you plan to use `HttpService` in it, to break the import loop.

**Comment by bursauxa** [comment] 2019-06-22 21:59
@Alexander-Fuchs was @sinedied's answer useful to you?

**Comment by sinedied** [comment] 2019-09-04 10:43
I'm closing it since we have no feedback on this, feel free to comment if it's not solved yet.

**Closed by sinedied** 2019-09-04 10:43 UTC
Labels: question
