### ISSUE TITLE
npm run build is failing

### ISSUE THREAD

**Issue by manoj000** [ngx-rocket/generator-ngx-rocket#188] opened 2017-11-24 15:48 UTC
## Environment

```
- generator version: X.Y.Z
- node version: v7.6.0  <!-- run `node --version` -->
- npm version: 4.1.1  <!-- run `npm --version` -->
- OS:  Mac <!-- Mac, Linux, Windows -->
```
<img width="637" alt="screen shot 2017-11-24 at 21 17 23" src="https://user-images.githubusercontent.com/3095717/33217277-422a77ae-d15d-11e7-9b81-9db661a6ff98.png">

**Comment by manoj000** [comment] 2017-11-24 15:51
[npm-debug.log](https://github.com/ngx-rocket/generator-ngx-rocket/files/1502093/npm-debug.log)


Npm log

**Comment by sinedied** [comment] 2017-11-24 16:08
What generator or CLI version did you use? With which options?

**Comment by manoj000** [comment] 2017-11-24 17:54
Genenrator : generator-ngx-rocket
with default options

**Comment by manoj000** [comment] 2017-11-24 18:00
here is my package.json file
{
  "name": "onboarding",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "ng": "ng",
    "build": "npm run env -s && ng build --prod",
    "start": "ng serve --proxy-config proxy.conf.js",
    "lint": "ng lint --type-check && stylelint \"src/**/*.scss\" --syntax scss && htmlhint \"src\" --config .htmlhintrc",
    "test": "ng test",
    "test:ci": "npm run lint -s && ng test --single-run --code-coverage",
    "e2e": "ng e2e",
    "translations:extract": "ngx-translate-extract --input ./src --output ./src/translations/template.json --format=json --clean -sort --marker extract",
    "docs": "hads ./docs -o",
    "env": "ngx-scripts env2json npm_package_version",
    "cordova:prepare": "ngx-scripts cordova prepare",
    "cordova:run": "ngx-scripts cordova run",
    "cordova:build": "ngx-scripts cordova build --device --release --copy dist",
    "cordova:clean": "ngx-scripts clean",
    "cordova": "cordova",
    "generate": "ng generate"
  },
  "dependencies": {
    "@angular/animations": "^4.2.6",
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/platform-browser": "^4.2.6",
    "@angular/platform-browser-dynamic": "^4.2.6",
    "@angular/router": "^4.2.6",
    "@angular/service-worker": "^1.0.0-beta.16",
    "@ionic-native/core": "^4.0.0",
    "@ionic-native/keyboard": "^4.0.0",
    "@ionic-native/splash-screen": "^4.0.0",
    "@ionic-native/status-bar": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "@ngx-translate/core": "^8.0.0",
    "angularfire2": "5.0.0-rc.3",
    "bootstrap": "4.0.0-beta",
    "core-js": "^2.4.1",
    "firebase": "^4.6.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "popper.js": "^1.12.9",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "cordova": "^7.0.0",
    "@angular/cli": "^1.4.2",
    "@angular/compiler-cli": "^4.2.6",
    "@angular/language-service": "^4.2.6",
    "@biesbjerg/ngx-translate-extract": "^2.3.1",
    "@ngx-rocket/scripts": "^1.0.4",
    "@types/jasmine": "^2.5.52",
    "@types/jasminewd2": "^2.0.2",
    "@types/lodash": "^4.14.52",
    "@types/node": "^8.0.10",
    "codelyzer": "~3.2.0",
    "hads": "^1.3.4",
    "htmlhint": "^0.9.13",
    "https-proxy-agent": "^2.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "^4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "~5.1.2",
    "puppeteer": "^0.11.0",
    "stylelint": "~8.1.0",
    "stylelint-config-recommended-scss": "~2.0.0",
    "stylelint-config-standard": "~17.0.0",
    "stylelint-scss": "~2.1.0",
    "ts-node": "^3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by manoj000** [comment] 2017-11-24 18:00
`{
  "name": "onboarding",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "ng": "ng",
    "build": "npm run env -s && ng build --prod",
    "start": "ng serve --proxy-config proxy.conf.js",
    "lint": "ng lint --type-check && stylelint \"src/**/*.scss\" --syntax scss && htmlhint \"src\" --config .htmlhintrc",
    "test": "ng test",
    "test:ci": "npm run lint -s && ng test --single-run --code-coverage",
    "e2e": "ng e2e",
    "translations:extract": "ngx-translate-extract --input ./src --output ./src/translations/template.json --format=json --clean -sort --marker extract",
    "docs": "hads ./docs -o",
    "env": "ngx-scripts env2json npm_package_version",
    "cordova:prepare": "ngx-scripts cordova prepare",
    "cordova:run": "ngx-scripts cordova run",
    "cordova:build": "ngx-scripts cordova build --device --release --copy dist",
    "cordova:clean": "ngx-scripts clean",
    "cordova": "cordova",
    "generate": "ng generate"
  },
  "dependencies": {
    "@angular/animations": "^4.2.6",
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/platform-browser": "^4.2.6",
    "@angular/platform-browser-dynamic": "^4.2.6",
    "@angular/router": "^4.2.6",
    "@angular/service-worker": "^1.0.0-beta.16",
    "@ionic-native/core": "^4.0.0",
    "@ionic-native/keyboard": "^4.0.0",
    "@ionic-native/splash-screen": "^4.0.0",
    "@ionic-native/status-bar": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "@ngx-translate/core": "^8.0.0",
    "angularfire2": "5.0.0-rc.3",
    "bootstrap": "4.0.0-beta",
    "core-js": "^2.4.1",
    "firebase": "^4.6.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "popper.js": "^1.12.9",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "cordova": "^7.0.0",
    "@angular/cli": "^1.4.2",
    "@angular/compiler-cli": "^4.2.6",
    "@angular/language-service": "^4.2.6",
    "@biesbjerg/ngx-translate-extract": "^2.3.1",
    "@ngx-rocket/scripts": "^1.0.4",
    "@types/jasmine": "^2.5.52",
    "@types/jasminewd2": "^2.0.2",
    "@types/lodash": "^4.14.52",
    "@types/node": "^8.0.10",
    "codelyzer": "~3.2.0",
    "hads": "^1.3.4",
    "htmlhint": "^0.9.13",
    "https-proxy-agent": "^2.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "^4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "~5.1.2",
    "puppeteer": "^0.11.0",
    "stylelint": "~8.1.0",
    "stylelint-config-recommended-scss": "~2.0.0",
    "stylelint-config-standard": "~17.0.0",
    "stylelint-scss": "~2.1.0",
    "ts-node": "^3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
`

**Comment by manoj000** [comment] 2017-11-24 18:03
<img width="492" alt="screen shot 2017-11-24 at 23 32 37 1" src="https://user-images.githubusercontent.com/3095717/33220639-deaddf3c-d16f-11e7-9d76-d4314439076b.png">

**Comment by sinedied** [comment] 2017-11-25 09:54
Try with the latest generator version:
```
npm rm -g generator-ngx-rocket
npm cache clean
npm i -g generator-ngx-rocket@latest
```

**Comment by manoj000** [comment] 2017-11-25 10:12
still the same error
 ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

**Comment by sinedied** [comment] 2017-11-25 10:18
What is your OS/version?
Could you also post the result of `npm ls -f --depth=0` on your system?

**Comment by sinedied** [comment] 2017-11-25 14:37
Just tried on my mac with the env as yours: `node@7.6.0` `npm@4.1.1` using [n](https://github.com/tj/n) to switch between node env, I cannot reproduce your issue.
Here's how I tested it:
```
yo ngx-rocket
(press enter to all questions)
npm run build
```

**Comment by sinedied** [comment] 2017-12-11 08:14
I'm closing this issue since I have no news from your side, feel free to comment if you still have problems.

**Closed by sinedied** 2017-12-11 08:14 UTC
