### ISSUE TITLE
Registration module 

### ISSUE THREAD

**Issue by 231293** [ngx-rocket/generator-ngx-rocket#203] opened 2017-12-16 17:11 UTC
I would love to see registration module in future update 
That should have all crud operations and listing (server side paging would be appreciated) with child attribute routes. 

Hope you will include this in future update

**Comment by sinedied** [comment] 2017-12-20 09:54
Duplicate of #186?

As for the backend part, this won't be covered in the core generator, but may be added through add-ons.

**Comment by bursauxa** [comment] 2018-11-20 15:13
Closing this for the reasons above.

**Closed by bursauxa** 2018-11-20 15:13 UTC
